# GAE benchmark results

In [1]:
import numpy as np
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

## AN2VEC

In [2]:
results = pd.read_csv('../data/behaviour/gae-benchmarks/lp-bias=[true, false]-sharedl1=[true, false]-'
                      'decadjdeep=[true, false]-dataset=[cora, citeseer, pubmed]-'
                      'overlap=[0, 8, 16]-testprop=[0.15, 0.30]-nsamples=10.csv.gz',
                      compression='gzip')
last_epoch = sorted(np.unique(results.epoch))[-1]
results = results[results.epoch == last_epoch]

In [3]:
averages = results.groupby(['bias', 'sharedl1', 'decadjdeep', 'dataset', 'overlap', 'blurring']).mean()
stds = results.groupby(['bias', 'sharedl1', 'decadjdeep', 'dataset', 'overlap', 'blurring']).std()

### Shared l1

In [4]:
averages.xs([False, True])\
    [['auc', 'ap']]\
    .stack().unstack([1, 4])\
    .reorder_levels(['blurring', 'decadjdeep', 'overlap']).sort_index()\
    [['cora', 'citeseer', 'pubmed']]

dataset                          cora            citeseer              pubmed  \
                                  auc        ap       auc        ap       auc
blurring decadjdeep overlap
0.15     False      0        0.928669  0.932253  0.940158  0.945510  0.950613
                    8        0.930294  0.935635  0.944549  0.948189  0.946433
                    16       0.932945  0.936042  0.948220  0.951456  0.930713
         True       0        0.883429  0.894645  0.908322  0.913254  0.917656
                    8        0.887484  0.896085  0.902848  0.909423  0.918967
                    16       0.892824  0.903344  0.904231  0.911761  0.920825
0.30     False      0        0.916112  0.924120  0.934943  0.938995  0.948759
                    8        0.918903  0.926251  0.935658  0.939858  0.941399
                    16       0.921719  0.928890  0.943262  0.948098  0.924663
         True       0        0.868274  0.880303  0.892681  0.900440  0.910215
                    8        0.865211  0.879828  0.896792  0.904109  0.911458
                    16       0.872229  0.884455  0.890310  0.895504  0.913918

dataset
                                   ap
blurring decadjdeep overlap
0.15     False      0        0.953707
                    8        0.948626
                    16       0.930576
         True       0        0.931821
                    8        0.930725
                    16       0.927513
0.30     False      0        0.950269
                    8        0.943468
                    16       0.923990
         True       0        0.924337
                    8        0.923809
                    16       0.920653

In [5]:
stds.xs([False, True])\
    [['auc', 'ap']]\
    .stack().unstack([1, 4])\
    .reorder_levels(['blurring', 'decadjdeep', 'overlap']).sort_index()\
    [['cora', 'citeseer', 'pubmed']]

dataset                          cora            citeseer              pubmed  \
                                  auc        ap       auc        ap       auc
blurring decadjdeep overlap
0.15     False      0        0.004995  0.007034  0.005996  0.005695  0.006221
                    8        0.003856  0.005355  0.007048  0.007055  0.005213
                    16       0.007901  0.007053  0.004446  0.004953  0.006167
         True       0        0.008031  0.008416  0.014037  0.015891  0.006894
                    8        0.016852  0.018730  0.013327  0.012892  0.004525
                    16       0.008851  0.010439  0.013957  0.012869  0.009610
0.30     False      0        0.007145  0.006813  0.003441  0.003182  0.003814
                    8        0.003457  0.003879  0.006418  0.007233  0.009610
                    16       0.006675  0.006816  0.006928  0.007518  0.006093
         True       0        0.012494  0.011262  0.012345  0.011420  0.003784
                    8        0.011779  0.010993  0.011018  0.010990  0.005377
                    16       0.010179  0.011519  0.024513  0.025013  0.006671

dataset
                                   ap
blurring decadjdeep overlap
0.15     False      0        0.005054
                    8        0.004407
                    16       0.005951
         True       0        0.005810
                    8        0.004613
                    16       0.009229
0.30     False      0        0.003474
                    8        0.009046
                    16       0.007091
         True       0        0.003233
                    8        0.004543
                    16       0.006568

### Unshared l1

In [6]:
averages.xs([False, False])\
    [['auc', 'ap']]\
    .stack().unstack([1, 4])\
    .reorder_levels(['blurring', 'decadjdeep', 'overlap']).sort_index()\
    [['cora', 'citeseer', 'pubmed']]

dataset                          cora            citeseer              pubmed  \
                                  auc        ap       auc        ap       auc
blurring decadjdeep overlap
0.15     False      0        0.916601  0.923915  0.919691  0.927372  0.965680
                    8        0.928870  0.935104  0.943409  0.947078  0.957962
                    16       0.932651  0.938988  0.951359  0.954687  0.935675
         True       0        0.880535  0.891037  0.883291  0.891384  0.911545
                    8        0.885794  0.895053  0.909604  0.916489  0.924394
                    16       0.889915  0.900254  0.904428  0.908407  0.927221
0.30     False      0        0.908178  0.917985  0.913309  0.921215  0.960803
                    8        0.919074  0.928667  0.937642  0.944440  0.951806
                    16       0.925996  0.934058  0.948390  0.953407  0.931460
         True       0        0.852377  0.863708  0.887003  0.895765  0.902380
                    8        0.866556  0.879738  0.896901  0.904233  0.911817
                    16       0.875652  0.887096  0.906065  0.913653  0.921670

dataset
                                   ap
blurring decadjdeep overlap
0.15     False      0        0.969072
                    8        0.959257
                    16       0.937016
         True       0        0.928493
                    8        0.936358
                    16       0.934089
0.30     False      0        0.964172
                    8        0.953308
                    16       0.930151
         True       0        0.919668
                    8        0.924154
                    16       0.928391

In [7]:
stds.xs([False, False])\
    [['auc', 'ap']]\
    .stack().unstack([1, 4])\
    .reorder_levels(['blurring', 'decadjdeep', 'overlap']).sort_index()\
    [['cora', 'citeseer', 'pubmed']]

dataset                          cora            citeseer              pubmed  \
                                  auc        ap       auc        ap       auc
blurring decadjdeep overlap
0.15     False      0        0.007002  0.006596  0.006838  0.007313  0.002308
                    8        0.005474  0.006348  0.005143  0.006403  0.003672
                    16       0.007582  0.006859  0.005590  0.005295  0.006327
         True       0        0.011750  0.012127  0.012768  0.012948  0.006618
                    8        0.015177  0.015717  0.010370  0.009894  0.002993
                    16       0.013341  0.012045  0.017095  0.020589  0.005223
0.30     False      0        0.007715  0.007088  0.008522  0.006905  0.001426
                    8        0.003609  0.004005  0.006929  0.006274  0.003647
                    16       0.003889  0.004303  0.004287  0.003986  0.006295
         True       0        0.007811  0.009460  0.014551  0.014217  0.006107
                    8        0.009111  0.008306  0.012865  0.012092  0.008067
                    16       0.007090  0.007909  0.010329  0.009728  0.002986

dataset
                                   ap
blurring decadjdeep overlap
0.15     False      0        0.002260
                    8        0.003106
                    16       0.007203
         True       0        0.005229
                    8        0.002054
                    16       0.005234
0.30     False      0        0.001344
                    8        0.003475
                    16       0.006671
         True       0        0.004534
                    8        0.007213
                    16       0.001869

## VGAE

In [8]:
results_vgae = pd.read_csv('../data/behaviour/gae-benchmarks/lp-vgae-'
                           'dataset=[cora, citeseer, pubmed]-testprop=[0.15, 0.30]-nsamples=10.csv.gz',
                           compression='gzip')
last_epoch = sorted(np.unique(results_vgae.epoch))[-1]
results_vgae = results_vgae[results_vgae.epoch == last_epoch]

In [9]:
averages_vgae = results_vgae.groupby(['dataset', 'blurring']).mean()
stds_vgae = results_vgae.groupby(['dataset', 'blurring']).std()

In [10]:
averages_vgae[['auc', 'ap']].stack().unstack([0, 2])[['cora', 'citeseer', 'pubmed']]

dataset       cora            citeseer              pubmed
               auc        ap       auc        ap       auc        ap
blurring
0.15      0.922591  0.928798  0.921745  0.930244  0.965447  0.968721
0.30      0.902977  0.913436  0.911954  0.919151  0.961535  0.964560

In [11]:
stds_vgae[['auc', 'ap']].stack().unstack([0, 2])[['cora', 'citeseer', 'pubmed']]

dataset       cora            citeseer              pubmed
               auc        ap       auc        ap       auc        ap
blurring
0.15      0.005550  0.005833  0.006499  0.006631  0.001501  0.001229
0.30      0.004795  0.004589  0.005465  0.005182  0.001503  0.001434